### ISSUE TITLE
paper_list query returns different results than on the website

### ISSUE THREAD

**Issue by kequach** [paperswithcode/paperswithcode-client#16]
When I run the query for "utrecht university" on the website (https://paperswithcode.com/search?q_meta=&q_type=&q=utrecht+university), I get 5 results in total: 
![image](https://user-images.githubusercontent.com/18238845/136260924-23407a9d-f6dd-42c3-a0a8-2c7091fafcc4.png)
When I run the same query, I get only 3 results and some of them are different results:
![image](https://user-images.githubusercontent.com/18238845/136261076-496a9fbf-a507-4685-a100-1c079e086407.png)

For example the paper I marked (see this link also: https://physics.paperswithcode.com/paper/long-lived-non-equilibrium-interstitial-solid) isn't even in the original query I did on the website. Is this an issue or am I using this wrong?

**Comment by alefnula** [comment]
Hi @kequach,

The frontpage search is not a paper search. It's a compound search over repositories and papers that's why it returns more results. It's also limited to only 200 results.

I added a `/search/` endpoint to the api that emulates the frontpage search. Also added a `.search` method on the client. Hope that solves your issue, and also sorry for a really late response.
